### ISSUE TITLE
"doens't seem to be linked " error in Expo-cli

### ISSUE THREAD

**Issue by Ninjalice** [mybigday/whisper.rn#13]
Hi ,  I am trying to use whisper.rn in an expo application and I get this error .  I have tried re-installing everything and I can't fix it, does anyone know why it could be.

I am new to this and so if someone could help me I would be very grateful.

Thank you very much.

```
 WARN  Possible Unhandled Promise Rejection (id: 0):
Error: The package 'whisper.rn' doesn't seem to be linked. Make sure:

- You rebuilt the app after installing the package
Error: The package 'whisper.rn' doesn't seem to be linked. Make sure:

- You rebuilt the app after installing the package
    at get (http://192.168.1.131:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:114469:22)
    at ?anon_0_ (http://192.168.1.131:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:114510:43)
    at next (native)
    at asyncGeneratorStep (http://192.168.1.131:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:4641:26)
    at _next (http://192.168.1.131:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:4660:29)
    at anonymous (http://192.168.1.131:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:4665:14)
    at tryCallTwo (/Users/kudo/01_Work/Repos/expo/expo/android/versioned-react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5a4n485h/x86/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/Users/kudo/01_Work/Repos/expo/expo/android/versioned-react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5a4n485h/x86/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/Users/kudo/01_Work/Repos/expo/expo/android/versioned-react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5a4n485h/x86/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (http://192.168.1.131:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:4657:25)
    at apply (native)
    at _initWhisper (http://192.168.1.131:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:114513:30)
    at apply (native)
    at initWhisper (http://192.168.1.131:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:114504:30)
    at ?anon_0_ (http://192.168.1.131:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:114793:50)
    at next (native)
    at asyncGeneratorStep (http://192.168.1.131:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:4641:26)
    at _next (http://192.168.1.131:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:4660:29)
    at tryCallOne (/Users/kudo/01_Work/Repos/expo/expo/android/versioned-react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5a4n485h/x86/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/Users/kudo/01_Work/Repos/expo/expo/android/versioned-react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5a4n485h/x86/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (http://192.168.1.131:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:29651:26)
    at _callTimer (http://192.168.1.131:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:29570:17)
    at _callReactNativeMicrotasksPass (http://192.168.1.131:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:29600:17)
    at callReactNativeMicrotasks (http://192.168.1.131:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:29763:44)
    at __callReactNativeMicrotasks (http://192.168.1.131:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:2793:46)
    at anonymous (http://192.168.1.131:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:2605:45)
    at __guard (http://192.168.1.131:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:2777:15)
    at flushedQueue (http://192.168.1.131:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:2604:21)
```

**Comment by jhen0409** [comment]
What is the Expo version? I've Expo 48 with `expo prebuild` and it works well.

**Comment by Ninjalice** [comment]
I have version 48 but i haven't done any expo prebuild or expo run:andoird , could that be it ?

**Comment by joiemoie** [comment]
Is it possible to run with react-native-web?

**Comment by UchennaOkafor** [comment]
@Ninjalice 
How were you able to get it to load the model? I'm having issues loading the model. I am using expo dev client, and I've tried loading the model from assets folder and that's not working. I'd really appreciate any help please
