### ISSUE TITLE
Can't start example app using command "yarn example start"

### ISSUE THREAD

**Issue by YasBenAll** [mybigday/whisper.rn#20]
I've followed the steps as described in the [development-workflow](https://github.com/mybigday/whisper.rn/blob/main/CONTRIBUTING.md#development-workflow), bur I'm running into the following error. What am I missing here?

```
C:\Users\User\Documents\GitHub\App\whisper.rn>yarn
➤ YN0070: Migrating from Yarn 1; automatically enabling the compatibility node-modules linker 👍

➤ YN0000: ┌ Resolution step
➤ YN0032: │ fsevents@npm:2.3.2: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ source-map-resolve@npm:0.5.3 is deprecated: See https://github.com/lydell/source-map-resolve#deprecated
➤ YN0061: │ urix@npm:0.1.0 is deprecated: Please see https://github.com/lydell/urix#deprecated
➤ YN0061: │ source-map-url@npm:0.4.1 is deprecated: See https://github.com/lydell/source-map-url#deprecated                                
➤ YN0061: │ @npmcli/move-file@npm:2.0.1 is deprecated: This functionality has been moved to @npmcli/fs
➤ YN0061: │ resolve-url@npm:0.2.1 is deprecated: https://github.com/lydell/resolve-url#deprecated
➤ YN0061: │ uglify-es@npm:3.3.9 is deprecated: support for ECMAScript is superseded by `uglify-js` as of v3.13.0
➤ YN0002: │ @fugood/eslint-config-base@npm:0.5.0 [d74be] doesn't provide @babel/core (paa0fe), requested by @babel/eslint-parser
➤ YN0002: │ react-native-codegen@npm:0.71.5 doesn't provide @babel/preset-env (pdcb72), requested by jscodeshift
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 9s 799ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ yargs@npm:15.4.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs@npm:16.2.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs@npm:17.7.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yn@npm:3.1.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yocto-queue@npm:0.1.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 2s 734ms
➤ YN0000: ┌ Link step
➤ YN0007: │ @evilmartians/lefthook@npm:1.3.5 must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 12s 167ms
➤ YN0000: Done with warnings in 24s 882ms

C:\Users\User\Documents\GitHub\App\whisper.rn>yarn example start
Internal Error: ENOENT: no such file or directory, lstat 'C:\Users\User\Documents\GitHub\App\whisper.rn\example\example'
    at realpathSync (node:fs:2503:7)
    at i (C:\Users\User\.node\corepack\yarn\3.4.1\yarn.js:446:12005)
    at async t (C:\Users\User\.node\corepack\yarn\3.4.1\yarn.js:446:10283)
    at async i (C:\Users\User\.node\corepack\yarn\3.4.1\yarn.js:446:12036)
    at async t (C:\Users\User\.node\corepack\yarn\3.4.1\yarn.js:446:10283)
```

**Comment by jhen0409** [comment]
This path doesn't look right. (example/example)

It seems an known issue from the latest version of Yarn. See https://github.com/yarnpkg/berry/issues/4908.

- Please use Yarn v1 first at this time.
- Otherwise, just try to run `yarn <cmd>` in `example/` instead of `yarn example <cmd>`

Also, I've updated the doc in de7b706ccf67fe284ebda3684c5ebd901c69eec3 to add the missing part, please notice the bootstrap script is included `yarn example` for install reps.
